### ISSUE TITLE
Projekte: all project images unavailable

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#90] opened 2019-06-19 15:39 UTC
waa waaaaa :(

eg http://codingdavinci.snater.com/de/projekte/math-models

**Comment by Snater** [comment] 2019-06-19 17:21
That was easy to fix. Just forgot to upload the images to the server.

**Comment by Snater** [comment] 2019-06-19 17:46
Reopening. There is still an issue with PNG images. These do not get processed.

**Comment by lucyWMDE** [comment] 2019-06-20 08:57
...a couple more problems - 

- the thumbnails on the landing page are coming up very small (compared to a fresh test project upload)
- the crop needs to be applied for the thumbnail on the project archive overview page.

not sure whether they can be fixed by you or if all images will need to be re-uploaded by hand 🙆🏻‍

**Comment by Snater** [comment] 2019-06-29 08:15
PNG actually seems to work, maybe that was just some temporary caching issue I had experienced.

Anyway, the thing about the project images was kind of strange at first and it's a bit of a silly problem. Could we just run the project import again or have you applied a lot of changes to the project entities?

The problem is that we introduced the special "project image" paragraph type (with that crop functionality) after I had written the import script and I forgot to update the script. So, when importing, the paragraph created for the project image was not of type "project image", but of the standard "attributed image" type. You can see that easily when editing an existing project: There is no crop functionality attached to the picture.

I tried to just erase an existing project's picture, but still the paragraph type seems to remain on "attributed image". I could try to tweak the database directly, but from my perspective, it would be a lot easier to just erase the projects again an then import with the correct paragraph type for the image. I hope you have not done too many changes on the projects so far, so we could do it that way. :-/
Otherwise I'd have a look if there was another solution.

**Comment by lucyWMDE** [comment] 2019-07-11 16:11
No changes have been made to the projects yet - you could go ahead and reimport. Pls go ahead :)

**Comment by Snater** [comment] 2019-07-13 08:39
Seems to be fine after re-importing.

**Comment by lucyWMDE** [comment] 2019-07-15 13:41
uuuh.. the re-import didn't include the info on which event the projects belong to... if you have the chance to run the import again in the next 1-2 days I'll wait. Otherwise I can do it by hand as I'll need to go through all the projects to add data anyway. thx

**Comment by Snater** [comment] 2019-07-15 17:47
It looks like the events were recreated leading to the references to the node ids hard-coded in the import script being outdated. I don't think I will have the chance to do the re-re-import before next weekend. Don't want to do that in a rush to not mix up things even more. :-/

**Comment by lucyWMDE** [comment] 2019-07-16 11:40
ok - then I'll do it by hand. not such a big deal considering I have to edit all projects anyway.

**Comment by lucyWMDE** [comment] 2019-07-18 15:12
in the end I didn't get around to work on the projects... spent my time mainly on the events page and writing you tickets.. ;)  I can still do this by hand if you're worried about creating further problems... but in case you think it's possible and it doesn't take much time an automatic import would definitely be faster.

**Comment by Snater** [comment] 2019-07-20 08:08
No problem. I have re-imported the projects; I hope they are correctly in place now, so closing again. :)

**Closed by Snater** 2019-07-20 08:08 UTC
Labels: bug, project
