### ISSUE TITLE
CSS-Dateien aggregieren should be possible

### ISSUE THREAD

**Issue by mbuechner** [codingdavinci/relaunch2018#196] opened 2020-03-10 12:02 UTC
To enhance the performance of the website the option 'CSS-Dateien aggregieren' under 'Leistung' should be enabled. If I do at the moment Drupal can't do the job correctly and the website is displayed without any CSS styling. This should be fixed!

https://www.drupal.org/project/minifyjs
https://www.drupal.org/project/minifyhtml

Both module are totally worth to install as well!

**Comment by Snater** [comment] 2020-06-27 16:58
At some point there was some problem with aggregating styles, yet the checkboxes on "Leistung" are ticked and CSS works correctly at the moment as far as I can see.

I don't see a real need for the modules. I'd rather opt for not having these as additional dependencies. We can try to enable BigPipe as per #197 which might have a more serious performance impact.

**Comment by mbuechner** [comment] 2020-08-14 12:34
Doesn't work on test.condingdavinci.de. kk

**Comment by mbuechner** [comment] 2020-09-03 11:00
We're using the Docker container build from https://github.com/codingdavinci/relaunch2018

If we need a `settings.local.php` (with any configuration) simply generate one in this repro, a new Docker container will be build and the we can deploy it to test.codingdavinci.de afterwards.

**Comment by Snater** [comment] 2020-09-05 19:35
There is no need for a `settings.local.php`. The question was rather if you might be setting up one separately for the deployment? But I guess you are not. Anyway, I just enabled the aggregation options on the test deployment and things seem to work?

**Comment by lucyWMDE** [comment] 2020-09-09 12:32
Not sure what this change might have affected... but we do now have a few problems

- link styles in the filters on the [dataset](https://test.codingdavinci.de/de/daten) and [project overview](https://test.codingdavinci.de/de/projekte) pages. Compare to [dataset](http://codingdavinci.snater.com/de/daten) and [project](http://codingdavinci.snater.com/de/projekte) on Henning's old development server - there should be several different styles (parent category, child category, hover, selected) but they all seem to have been overridden.
- menu hamburger no longer responds to being clicked on  [dataset](https://test.codingdavinci.de/de/daten) and [project overview](https://test.codingdavinci.de/de/projekte) pages

I've had a cursory look around the site and can't find anything else that's a problem. But perhaps @mbuechner has suggestions of where else to do more detailed testing?

**Comment by mbuechner** [comment] 2020-09-10 11:47
> 
> 
>Anyway, I just enabled the aggregation options on the test deployment and things seem to work?

Nope, still doesn't work! Don't forget to clear cache after enabling/disabling aggregation.

**Comment by mbuechner** [comment] 2020-09-10 15:28
Aggregation of JS files does work neither.

If you enable the menu at https://test.codingdavinci.de/de/projekte doesn't work. 😢

**Comment by lucyWMDE** [comment] 2020-09-10 15:33
I don't know what you did @mbuechner but the menu hamburger is back on dataset and project overview pages now, at least for me (on firefox).
Filter link styles still need fixing.

**Comment by Snater** [comment] 2020-09-12 17:59
I fail to reproduce this. Enabling aggregation, clearing all Drupal caches, hard-reloading the browser, things work. Chrome. Firefox.
Maybe I am fundamentally misunderstanding this issue?

**Comment by lucyWMDE** [comment] 2020-09-14 14:33
in the filter (left sidebar) there should be many tag link styles, as seen on http://codingdavinci.snater.com/de/daten
![image](https://user-images.githubusercontent.com/42772674/93098533-4244d500-f6a7-11ea-9128-aa4675a0d9f3.png)

Instead all tag link styles are overridden, as seen on https://test.codingdavinci.de/de/daten
![image](https://user-images.githubusercontent.com/42772674/93098763-83d58000-f6a7-11ea-9bd5-683cd5f07d99.png)

This is true for both the dataset overview page and the project overview page. As I said - I'm not sure if this bug is related to CSS aggregation... if it should have it's own ticket please create one.

The menu hamburger issue no longer seems to be a problem. I can't comment on any other issues. Maybe @mbuechner has something to add?

**Comment by lucyWMDE** [comment] 2020-09-14 15:50
sorry - I'm not sure where this filter tag link styles problem belongs... I've also referred to it in issue #242. 
I don't know of any further CSS aggregation issues and leave it to @mbuechner to comment or close this issue if everything is resolved.

**Comment by Snater** [comment] 2020-09-19 14:29
The filter styles were indeed an effect of #242, but were fixed per https://github.com/codingdavinci/relaunch2018/commit/95c81707e1baa4e84f24fa96c30a19375677162d yet either the deployment took a while or things were just cached. Anyway, it seems to be correct on the test deployment now.

As for the aggregation of styles and JS:
![cdv_css](https://user-images.githubusercontent.com/24992120/93669498-fc1bb700-fa94-11ea-8e52-3e48099aa6b0.PNG)
![cdv_js](https://user-images.githubusercontent.com/24992120/93669500-fd4ce400-fa94-11ea-8e2d-43b4ae584a74.PNG)
This is as expected, except for that one 404 which I have not experienced anytime before. Might be related to some config change? Anyway it would be a new issue.

I'm closing this again.

**Closed by Snater** 2020-09-19 14:29 UTC
Labels: bug, enhancement
