### ISSUE TITLE
Problem with event team user accounts

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#106] opened 2019-07-16 14:11 UTC
seems to be weird... I tested for "Testmanager" and even made a new "Testmanager2" to check. Wanted to test event page content development but, when logged in, I get the "The website encountered an unexpected error. Please try again later." error message when I try to access Content.

**Comment by Snater** [comment] 2019-07-20 09:48
That seems to have been caused by outdated event references. Added a sanity check catching such cases.

**Comment by lucyWMDE** [comment] 2019-07-25 16:01
Just tested them out - these event team users don't seem to be configured right. Should be able to:
- save event page as Entwurf
- edit projects (can't remember if only from their region, or if it had to be all)
- edit datasets (can't remember if only from their region, or if it had to be all)

**Comment by Snater** [comment] 2019-07-27 07:57
> * go back to a previously created event page, make edits, then save as Entwurf (the option is not there)

That seems to have been some misconfigured permission. Should be fixed along with https://github.com/codingdavinci/relaunch2018/commit/ec6149734f63cf35be2ec91478bc3b067d0beec1

> * edit projects (can't remember if only from their region, or if it had to be all)
> * edit datasets (can't remember if only from their region, or if it had to be all)

I did not check that in detail, but when I log in as Testmanager I am able to edit some projects and data sets, so I assume it is implemented that event managers may edit such nodes that are assigned to their event(s).

> * this user shouldn't be able to make a new event. The Geschäftstelle or Admin accounts should be the only ones able to do that (fwiw when I do try to create a new event it does really weird stuff like create a new event page every time I hit save, rather than just a version of the same page).

OK, revoked the permissions to create new events with the commit above.

Regarding creating new events on every save: You might have created a new event and used the back button? This leads you back to the creation page (`/node/add/event`), so it would be expected behaviour to have a new event node created in that case.

**Closed by Snater** 2019-07-27 07:57 UTC
Labels: bug
